version: "3.5"
x-buildargs:
    &default-buildargs
    BASE_IMAGE: alpine
    BASE_IMAGE_TAG: 3.14
    NODE_VER: 14.19.0-r0
    NPM_VER: 7.17.0-r0
    PM2_VER: 5.1.1
volumes:
    temp_data:
services:
    dev:
        image: react/app:dev
        ports: 
            - "5005:80"    # Vanilla watch `npm run watch`
            - "5055:5055"  # Hot reloading server `npm run reloader`
        build:
            context: .
            target: src
            args: *default-buildargs
        volumes:
            - "${FOLDER_LOCATION:-.}/src:/home/app/src"
            - "${FOLDER_LOCATION:-.}/server:/home/app/server"
            - "${FOLDER_LOCATION:-.}/docker-compose.yml:/home/app/docker-compose.yml"
        env_file:
            - "${COMPOSE_ENV_FILE:-.env.tmpl}"
        environment:
            DEV_DATABASE_URL: "mongodb://mongodb:27017/${MONGO_DB_NAME:-mongo}"
            LOG_EVERY_NUM_CHECKS: 5
            DEV_ENV:          "true"
            ENABLE_DB:        "false"
        ###! Uncomment to bring up the mongodb service
        ###! Also set ENABLE_DB to "true" - See server/routes.js to adjust behavior
        #depends_on:
        #    - mongodb
 
    #### Dev DB service ===
    mongodb:
        image: mongo:4.4.6
        ports: ["27017:27017"]
        restart: on-failure
        environment:
            MONGO_INITDB_DATABASE: "${MONGO_DB_NAME:-mongo}"
        volumes:
            - temp_data:/data/db
    ###############################################################
    ###############################################################
    main:
        image: registry.codeopensrc.com/os/react-template/app:0.5.0-0ff4c24
        ports: ["5000:80"]
        labels: ["com.codeopensrc.consul=react"]
        build:
            context: .
            target: prod
            args: *default-buildargs
        env_file:
            - "${COMPOSE_ENV_FILE:-.env.tmpl}"
        environment:
            CONSUL_SERVICE_NAME:    "react"
            REGISTER_SERVICE:       "false"
            ENABLE_DB:              "false"
        ## Docker Swarm - https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy
        ## deploy:
