version: "3.5"
services:
    main:
        build:
            context: .
            target: src
        image: jestrr/react:0.1.0
        entrypoint: ["pm2-dev", "server/pm2.config.js"]
        volumes:
            - ./src:/home/app/src
            - ./server:/home/app/server
            - ./docker-compose.override.yml:/home/app/docker-compose.yml
        ports:
            - "5005:80"
        labels:
            com.consul.service: base_react_app
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
                max_failure_ratio: 1
                order: start-first
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az
        healthcheck:
            test: exit $$(curl -sS http://localhost/healthcheck; echo $$?)
            interval: 5s
            timeout: 2s
            start_period: 5s
        environment:
            DEV_DATABASE_URL: "mongodb://172.17.0.1:27017/mymongo"
            USE_CONSUL_DB:          "false"
            REGISTER_SERVICE:       "false"
            USE_AUTH:               "false"
            AUTH_URL:               ""
            LOG_EVERY_NUM_CHECKS:   5
            DEV_ENV:                "true"
