apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: react-template
build:
  artifacts:
    - image: registry.codeopensrc.com/os/react-template/app
      context: .
      docker:
        target: src
        buildArgs:
          BASE_IMAGE: alpine
          BASE_IMAGE_TAG: 3.14
          NODE_VER: 14.19.0-r0
          NPM_VER: 7.17.0-r0
          PM2_VER: 5.1.1
      sync:
        manual:
          - src: "src/**"
            dest: /home/app
          - src: "server/**"
            dest: /home/app
          - src: "docker-compose.yml"
            dest: /home/app
deploy:
  helm:
    releases:
    - name: react-template
      namespace: react
      createNamespace: true
      chartPath: helmchart
      artifactOverrides:
        image: registry.codeopensrc.com/os/react-template/app
      overrides:
        replicaCount: 1
        image:
          pullPolicy: IfNotPresent
        service:
          ports:
            - servicePort: 80
              targetContainerPortName: http
            - servicePort: 5055
              targetContainerPortName: reloader
        containerPorts: 
          - name: http
            port: 80
          - name: reloader
            port: 5055
        lifecyclePostStartCommand:
          ["sh", "-c", "npm run reloader > /var/log/hotreload.log &"]
        volumeMounts:
          - name: shared-logs
            mountPath: /var/log
        additionalContainers:
          - name: hotreload-logger
            image: busybox
            command: ["sh", "-c", 
              "while [ ! -f /var/log/hotreload.log ]; do sleep 1; done; \
               tail -f /var/log/hotreload.log"
            ]
            volumeMounts:
              - name: shared-logs
                mountPath: /var/log
      imageStrategy:
        helm: {}
      setFiles:
        dotEnvFile: .env
      setValues:
        configMapData.DEV_DATABASE_URL_ORIGIN: "mongodb://mongodb:27017"
        configMapData.LOG_EVERY_NUM_CHECKS: 5
        configMapData.DEV_ENV:   "true"
        configMapData.ENABLE_DB: "false"
        configMapData.LIVE_RELOADER_PORT: 5055
