## Yaml anchors
.sync: &sync
  manual:
  - src: "src/**"
    dest: /home/app
  - src: "server/**"
    dest: /home/app
  - src: "docker-compose.yml"
    dest: /home/app

.custom_build_deps: &custom_build_deps
  paths:
  - src/**
  - server/**
  - Dockerfile
  ignore:
  - "**/*.swp"

.helm_flags: &helm_flags
  install: ["--timeout=300s"]
  upgrade: ["--timeout=300s"]

### Main config
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: react-template
profiles:
### Build locally and deploy to minikube or remote cluster
- name: docker
  activation:
  - kubeContext: minikube
  build:
    ### Uncomment when deploying to remote cluster
    ### Not recommended to push if deploying to local minikube
    #local:
    #  push: true
    artifacts:
      - image: registry.codeopensrc.com/os/react-template/app
        context: .
        custom:
          buildCommand: ./build.sh buildx
          dependencies: *custom_build_deps
        sync: *sync
  deploy:
    ### Deploy to specific context
    #kubeContext: "minikube"
    helm:
      flags: *helm_flags
      releases:
      - name: react
        namespace: skaffold-react
        createNamespace: true
        chartPath: charts/react
        wait: true
        valuesFiles:
        - skaffold/remote/react-db-values.yaml
        - skaffold/remote/react-template-values.yaml
        ## To pass in a local .env file
        #setFiles:
        #  dotEnvFile: .env


### Build remotely and deploy to remote cluster
- name: remote
  build:
    local:
      push: true
    artifacts:
      - image: registry.codeopensrc.com/os/react-template/app
        context: .
        custom:
          ### './build.sh ctl' or './build.sh remote_buildx'
          buildCommand: ./build.sh ctl
          dependencies: *custom_build_deps
        sync: *sync
  deploy:
    helm:
      flags: *helm_flags
      releases:
      - name: react
        namespace: skaffold-react
        createNamespace: true
        chartPath: charts/react
        wait: true
        valuesFiles:
        - skaffold/remote/react-db-values.yaml
        - skaffold/remote/react-template-values.yaml
        ## To pass in a local .env file
        #setFiles:
        #  dotEnvFile: .env


### Build remotely and deploy to remote cluster with 3 replicated mongo databases
- name: replica
  build:
    local:
      push: true
    artifacts:
      - image: registry.codeopensrc.com/os/react-template/app
        context: .
        custom:
          buildCommand: ./build.sh ctl
          dependencies: *custom_build_deps
        sync: *sync
  deploy:
    helm:
      flags: *helm_flags
      releases:
      - name: react
        namespace: skaffold-react
        createNamespace: true
        chartPath: charts/react
        wait: true
        valuesFiles:
        - skaffold/replica/react-db-values.yaml
        - skaffold/replica/react-template-values.yaml


### Meant for ci builds
### WIP
- name: ci
  build:
    local:
      push: true
    artifacts:
      ### TODO: CUSTOM REGISTRY
      ### Might have to sed this...
      - image: registry.codeopensrc.com/os/react-template/app
        context: .
        custom:
          buildCommand: ./build.sh ctl prod
  deploy:
    helm:
      flags: *helm_flags
      releases:
      - name: "{{.APPNAME}}"
        namespace: "{{.KUBE_NAMESPACE}}"
        createNamespace: true
        chartPath: charts/react
        wait: true
        valuesFiles:
        ### TODO: Review value files for ci
        #- skaffold/ci/react-db-values.yaml
        ## TODO: helm_ci_values.yaml for db
        #- skaffold/ci/react-template-values.yaml
        #- helm_ci_values.yaml
