replicaCount: 3
image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: 4.4.6
command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
service:
  type: None
  ports:
    - servicePort: 27017
      targetContainerPortName: mongo
ingress:
  enabled: false
containerPorts:
  - name: mongo
    port: 27017
containerProbe: ""
useStatefulSet: true
statefulSetPodManagementPolicy: "Parallel"
job:
  enabled: true
  image:
    repository: mongo
    pullPolicy: Always
    tag: "4.4.6"
  backoffLimit: 0
  restartPolicy: Never
  command:
  - bash
  - -c
  - |
    mongo --host "react-db-0.react-db" --eval \
      "rs.initiate( { _id : 'rs0', members: [
          { _id: 0, host: 'react-db-0.react-db:27017' },
          { _id: 1, host: 'react-db-1.react-db:27017' },
          { _id: 2, host: 'react-db-2.react-db:27017' }
      ]})";
persistence:
  statefulset:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Delete
volumeClaimMounts:
  - mountPath: /data/db
    subPath: db
secretStringData:
  MONGO_INITDB_DATABASE: mongo
configMapData: {}
