{{- if .Values.configMapData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "react-template.fullname" . }}
  labels:
    {{- include "react-template.labels" . | nindent 4 }}
    {{- with .Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $k, $v := .Values.configMapData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
