{{- range .Values.createExtraConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace .namespace }}
  labels:
    {{- include "react-template.labels" $ | nindent 4 }}
    {{- with $.Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $k, $v := .data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
