apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-template.fullname" . }}
  labels:
    {{- include "react-template.labels" . | nindent 4 }}
    {{- with .Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ciAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq .Values.service.type "None" }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .servicePort }}
      targetPort: {{ .targetContainerPortName }}
      protocol: {{ default "TCP" .proto }}
      name: {{ .targetContainerPortName }}
    {{- end }}
  selector:
    {{- include "react-template.selectorLabels" . | nindent 4 }}
