apiVersion: v2
name: react
description: Helm chart for react+mongodb application
type: application
###! For now tieing tpl and react chart versioning together
version: 0.6.1
###! Follows the version in docker-compose.yml
###! Updated in CI and should not need manual updates
appVersion: "0.8.0-b626d6f"
## Cannot share data between dependency charts using 'import-values'
## Data imported only available to manifests in this charts templates/ folder
dependencies:
- name: tpl
  version: 0.6.1
  alias: app
  condition: app.enabled
  ##! Dependency location for dev
  repository: file://../tpl
  ##! Dependency location when packaged in helm chart repository
  #repository: https://gitlab.codeopensrc.com/api/v4/projects/36/packages/helm/stable
- name: tpl
  version: 0.6.1
  alias: db
  condition: db.enabled
  ##! Dependency location for dev
  repository: file://../tpl
  ##! Dependency location when packaged in helm chart repository
  #repository: https://gitlab.codeopensrc.com/api/v4/projects/36/packages/helm/stable
