{{- range .Values.createAndAttachExtraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "react-template.labels" $ | nindent 4 }}
    {{- with $.Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- range $k, $v := .stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
