{{- if .Values.persistence.deployment.enabled }}
{{- $claim := .Values.persistence.deployment.volumeTemplate }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "react-template.fullname" . }}
  labels:
    {{- include "react-template.labels" . | nindent 4 }}
  annotations:
    {{- if $claim.helmResourcePolicy }}
    helm.sh/resource-policy: {{ default "keep" $claim.helmResourcePolicy }}
    {{- end }}
spec:
  accessModes: {{ $claim.accessModes }}
  volumeMode: {{ $claim.volumeMode }}
  storageClassName: {{ $claim.storageClassName }}
  resources:
    {{- toYaml $claim.resources | nindent 4 }}
  selector:
    matchLabels:
      {{- include "react-template.selectorLabels" . | nindent 6 }}
---
{{- end }}
