{{- if .Values.secretStringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "react-template.fullname" . }}
  labels:
    {{- include "react-template.labels" . | nindent 4 }}
    {{- if .Values.appLabel }}
    app: {{ .Values.appLabel }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secretStringData | nindent 2 }}
---
{{- end }}

{{- range .Values.createExtraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "react-template.labels" $ | nindent 4 }}
    {{- if $.Values.appLabel }}
    app: {{ $.Values.appLabel }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .stringData | nindent 2 }}
---
{{- end }}
