{{- if .Values.secretStringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "react-template.fullname" . }}
  labels:
    {{- include "react-template.labels" . | nindent 4 }}
    {{- with .Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secretStringData | nindent 2 }}
{{- end }}
